#!/bin/bash

dir="$(pwd)/articles"
cd $dir

rm -rfv *.pdf
cp '/home/mitsuki/Documents/Zotero Library Sync/brown2012.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.3390@healthcare8020133.pdf' '/home/mitsuki/Documents/Zotero Library Sync/wynia2011.pdf' '/home/mitsuki/Documents/Zotero Library Sync/asghar2017.pdf' '/home/mitsuki/Documents/Zotero Library Sync/rasmussen2016.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.1177@1359105320967085.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.1080@00224499.2018.1556772.pdf' .
cp '/home/mitsuki/Documents/Zotero Library Sync/d2ra01788a.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.1016@j.asoc.2014.02.002.pdf' '/home/mitsuki/Documents/Zotero Library Sync/mohammadpour2014.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Loh - 2019 - A Simple Proof of the Quadratic Formula.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Intelligent_model_for_predicting_water_q.pdf' '/home/mitsuki/Documents/Zotero Library Sync/NCRI_Twitter-Report_8.29.pdf' '/home/mitsuki/Documents/Zotero Library Sync/unger2013.pdf' '/home/mitsuki/Documents/Zotero Library Sync/sun2020.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.1007@s11069-019-03573-9.pdf' '/home/mitsuki/Documents/Zotero Library Sync/kearby2020.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.1080@19477503.2019.1595360.pdf' '/home/mitsuki/Documents/Zotero Library Sync/10.1016@j.chaos.2020.109846.pdf' '/home/mitsuki/Documents/Zotero Library Sync/jiang2019.pdf' .
cp '/home/mitsuki/Documents/Zotero Library Sync/Paragas_Francisco/Paragas and Francisco - 2020 - Utilizing Social Media in Improving Creative Writi.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Lakhal/Lakhal - 2022 - The Role of social media in Developing English Lan.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Klimova_Pikhart/Klimova and Pikhart - 2019 - Cognitive and Applied Linguistics Aspects of Using.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Al-Jarrah et al/Al-Jarrah et al. - 2019 - The Role of Social Media in Development of English.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Bakeer/Bakeer - 2018 - Effects of Information and Communication Technolog.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Kabilan et al/Kabilan et al. - 2010 - Facebook An online environment for learning of En.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Derakhshan_Hasanabbasi/Derakhshan and Hasanabbasi - 2015 - Social Networks for Language Learning.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Jaakonmäki et al/Jaakonmäki et al. - 2017 - The Impact of Content, Context, and Creator on Use.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Arriagada_Ibáñez/Arriagada and Ibáñez - 2020 - “You Need At Least One Picture Daily, if Not, You’.pdf' .
cp '/home/mitsuki/Documents/Zotero Library Sync/Ingram/Ingram_Self-Focused Attention in Clinical Disorders.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Laperdrix et al/Laperdrix et al_2016_Beauty and the Beast.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Martin_Cohen/Martin_Cohen_2023_“Welcome to the stream, Vykaryous4Eva.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Meng_Marcos/Meng_Marcos_Ridesharing Evacuation Model of Disaster Response.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Mor_Winquist/Mor_Winquist_2002_Self-focused attention and negative affect.pdf' '/home/mitsuki/Documents/Zotero Library Sync/N et al/N et al_2017_Electronic Health Record Management.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Padgette et al/Padgette et al_2022_Guide to Bluetooth Security.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Reingold/Reingold_2005_Undirected ST-connectivity in log-space.pdf' '/home/mitsuki/Documents/Zotero Library Sync/Sjöwall et al/Sjöwall et al_2013_Multiple deficits in ADHD.pdf' .
